export const BUSINESS = {
  name: 'Advanced Concrete of Dallas',
  shortName: 'Advanced Concrete',
  tagline: 'Dallas-Fort Worth’s Trusted Concrete Contractor',
  city: 'Dallas',
  state: 'TX',
  phone: '(214) 466-6247',
  phoneHref: 'tel:+12144666247',
  email: 'info@advancedconcretedallas.com',
  hours: 'Mon–Sat 7am–6pm',
  addressLine: '1402 Fort Worth Ave, Dallas, TX 75208',
  streetAddress: '1402 Fort Worth Ave',
  postalCode: '75208',
  license: 'Licensed & Insured General Contractor — TX',
  siteUrl: 'https://advancedconcretedallas.com',
  founded: 2009,
} as const
